// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTZKplGKefPpbnJHK8fBeXjVhK2aTD7Y',
    appId: '1:976192093032:web:bad8ca9be8c7675b0174dd',
    messagingSenderId: '976192093032',
    projectId: 'beginnerapp-fa4d3',
    authDomain: 'beginnerapp-fa4d3.firebaseapp.com',
    storageBucket: 'beginnerapp-fa4d3.appspot.com',
    measurementId: 'G-ZHNB14D4FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA24ah5o65y7GUiMOSeNTRc9JO_V2ais8Q',
    appId: '1:976192093032:android:730a78ac7503d0e90174dd',
    messagingSenderId: '976192093032',
    projectId: 'beginnerapp-fa4d3',
    storageBucket: 'beginnerapp-fa4d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9OqJzcN13Q3_YKJBKppkKg4guOGkJrPU',
    appId: '1:976192093032:ios:8975c7485383db040174dd',
    messagingSenderId: '976192093032',
    projectId: 'beginnerapp-fa4d3',
    storageBucket: 'beginnerapp-fa4d3.appspot.com',
    iosBundleId: 'com.example.beginnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9OqJzcN13Q3_YKJBKppkKg4guOGkJrPU',
    appId: '1:976192093032:ios:8975c7485383db040174dd',
    messagingSenderId: '976192093032',
    projectId: 'beginnerapp-fa4d3',
    storageBucket: 'beginnerapp-fa4d3.appspot.com',
    iosBundleId: 'com.example.beginnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnTZKplGKefPpbnJHK8fBeXjVhK2aTD7Y',
    appId: '1:976192093032:web:edf51ce2cb8feb5f0174dd',
    messagingSenderId: '976192093032',
    projectId: 'beginnerapp-fa4d3',
    authDomain: 'beginnerapp-fa4d3.firebaseapp.com',
    storageBucket: 'beginnerapp-fa4d3.appspot.com',
    measurementId: 'G-7LXYEYP62Q',
  );

}